name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install

    - name: Build datasets
      run: |-
        poetry run python build.py
    
    - name: Deploy datasets to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT: slothful-myles
        VERCEL_SCOPE: team_zMUI4sQyIJCEJwCyZPlYaQ1b
      run: |-
        poetry run datasette publish vercel *.db \
          --metadata metadata.json
          --token $VERCEL_TOKEN \
          --project $VERCEL_PROJECT \
          --scope $VERCEL_SCOPE
